import type { GoodsReceiptFormValues } from '../schemas/goods-receipt.schema'
import type { GoodsReceipt } from '../types/goods-receipt.types'

let receipts: GoodsReceipt[] = [
  {
    id: crypto.randomUUID(),
    code: 'PNK-20260601-001',
    warehouseName: 'Kho tổng Hà Nội',
    supplierName: 'Công ty TNHH Thiết bị Văn phòng Minh Long',
    receiptDate: '2026-06-01',
    unitName: 'CÔNG TY TNHH GIẢI PHÁP SỐ',
    department: 'Phòng hành chính',
    delivererName: 'Trần Văn Bình',
    invoiceNumber: 'HD-2026-0601',
    invoiceDate: '2026-06-01',
    debitAccount: '1521',
    creditAccount: '331',
    attachedDocuments: 'Hoá đơn GTGT 0601',
    amountInWords: 'Bốn triệu không trăm năm mươi nghìn đồng chẵn',
    warehouseLocation: '',
    items: [
      {
        productName: 'Giấy A4 Double A 80gsm',
        productCode: 'VT-001',
        unit: 'Ram',
        quantity: 20,
        price: 78500,
      },
      {
        productName: 'Mực in laser đen HP 76A',
        productCode: 'VT-014',
        unit: 'Hộp',
        quantity: 2,
        price: 1240000,
      },
    ],
    totalAmount: 20 * 78500 + 2 * 1240000,
    createdAt: '2026-06-01T08:00:00.000Z',
  },
  {
    id: crypto.randomUUID(),
    code: 'PNK-20260605-002',
    warehouseName: 'Kho tổng Hà Nội',
    supplierName: 'Nhà phân phối Đông Á',
    receiptDate: '2026-06-05',
    unitName: 'CÔNG TY TNHH GIẢI PHÁP SỐ',
    department: 'Phòng kho vận',
    delivererName: 'Nguyễn Thị Hoa',
    invoiceNumber: 'HD-2026-0605',
    invoiceDate: '2026-06-05',
    debitAccount: '1521',
    creditAccount: '331',
    attachedDocuments: 'Hoá đơn GTGT 0605',
    amountInWords: 'Hai triệu một trăm nghìn đồng chẵn',
    warehouseLocation: '',
    items: [
      {
        productName: 'Bìa hồ sơ còng 7cm',
        productCode: 'VT-028',
        unit: 'Cái',
        quantity: 50,
        price: 42000,
      },
    ],
    totalAmount: 50 * 42000,
    createdAt: '2026-06-05T09:00:00.000Z',
  },
  {
    id: crypto.randomUUID(),
    code: 'PNK-20260612-003',
    warehouseName: 'Kho miền Nam',
    supplierName: 'Văn phòng phẩm Hồng Hà',
    receiptDate: '2026-06-12',
    unitName: 'CÔNG TY TNHH GIẢI PHÁP SỐ',
    department: 'Phòng hành chính',
    delivererName: 'Lê Văn Cường',
    invoiceNumber: 'HD-2026-0612',
    invoiceDate: '2026-06-12',
    debitAccount: '1521',
    creditAccount: '331',
    attachedDocuments: 'Hoá đơn GTGT 0612',
    amountInWords: 'Hai triệu bốn trăm ba mươi bảy nghìn năm trăm đồng chẵn',
    warehouseLocation: 'KCN Tân Bình, TP. Hồ Chí Minh',
    items: [
      {
        productName: 'Giấy A4 Double A 80gsm',
        productCode: 'VT-001',
        unit: 'Ram',
        quantity: 15,
        price: 78500,
      },
      {
        productName: 'Bìa hồ sơ còng 7cm',
        productCode: 'VT-028',
        unit: 'Cái',
        quantity: 30,
        price: 42000,
      },
    ],
    totalAmount: 15 * 78500 + 30 * 42000,
    createdAt: '2026-06-12T09:30:00.000Z',
  },
  {
    id: crypto.randomUUID(),
    code: 'PNK-20260620-004',
    warehouseName: 'Kho tổng Hà Nội',
    supplierName: 'Công ty TNHH Thiết bị Văn phòng Minh Long',
    receiptDate: '2026-06-20',
    unitName: 'CÔNG TY TNHH GIẢI PHÁP SỐ',
    department: 'Phòng kho vận',
    delivererName: 'Trần Văn Bình',
    invoiceNumber: 'HD-2026-0620',
    invoiceDate: '2026-06-20',
    debitAccount: '1521',
    creditAccount: '331',
    attachedDocuments: 'Hoá đơn GTGT 0620',
    amountInWords: 'Ba triệu bảy trăm hai mươi nghìn đồng chẵn',
    warehouseLocation: '',
    items: [
      {
        productName: 'Mực in laser đen HP 76A',
        productCode: 'VT-014',
        unit: 'Hộp',
        quantity: 3,
        price: 1240000,
      },
    ],
    totalAmount: 3 * 1240000,
    createdAt: '2026-06-20T10:00:00.000Z',
  },
  {
    id: crypto.randomUUID(),
    code: 'PNK-20260701-005',
    warehouseName: 'Kho miền Nam',
    supplierName: 'Nhà phân phối Đông Á',
    receiptDate: '2026-07-01',
    unitName: 'CÔNG TY TNHH GIẢI PHÁP SỐ',
    department: 'Phòng hành chính',
    delivererName: 'Nguyễn Thị Hoa',
    invoiceNumber: 'HD-2026-0701',
    invoiceDate: '2026-07-01',
    debitAccount: '1521',
    creditAccount: '331',
    attachedDocuments: 'Hoá đơn GTGT 0701',
    amountInWords: 'Ba triệu hai trăm lẻ hai nghìn năm trăm đồng chẵn',
    warehouseLocation: '',
    items: [
      {
        productName: 'Giấy A4 Double A 80gsm',
        productCode: 'VT-001',
        unit: 'Ram',
        quantity: 25,
        price: 78500,
      },
      {
        productName: 'Mực in laser đen HP 76A',
        productCode: 'VT-014',
        unit: 'Hộp',
        quantity: 1,
        price: 1240000,
      },
    ],
    totalAmount: 25 * 78500 + 1 * 1240000,
    createdAt: '2026-07-01T08:30:00.000Z',
  },
  {
    id: crypto.randomUUID(),
    code: 'PNK-20260710-006',
    warehouseName: 'Kho tổng Hà Nội',
    supplierName: 'Văn phòng phẩm Hồng Hà',
    receiptDate: '2026-07-10',
    unitName: 'CÔNG TY TNHH GIẢI PHÁP SỐ',
    department: 'Phòng kho vận',
    delivererName: 'Lê Văn Cường',
    invoiceNumber: 'HD-2026-0710',
    invoiceDate: '2026-07-10',
    debitAccount: '1521',
    creditAccount: '331',
    attachedDocuments: 'Hoá đơn GTGT 0710',
    amountInWords: 'Một triệu sáu trăm tám mươi nghìn đồng chẵn',
    warehouseLocation: '',
    items: [
      {
        productName: 'Bìa hồ sơ còng 7cm',
        productCode: 'VT-028',
        unit: 'Cái',
        quantity: 40,
        price: 42000,
      },
    ],
    totalAmount: 40 * 42000,
    createdAt: '2026-07-10T09:00:00.000Z',
  },
  {
    id: crypto.randomUUID(),
    code: 'PNK-20260715-007',
    warehouseName: 'Kho tổng Hà Nội',
    supplierName: 'Công ty TNHH Thiết bị Văn phòng Minh Long',
    receiptDate: '2026-07-15',
    unitName: 'CÔNG TY TNHH GIẢI PHÁP SỐ',
    department: 'Phòng hành chính',
    delivererName: 'Trần Văn Bình',
    invoiceNumber: 'HD-2026-0715',
    invoiceDate: '2026-07-15',
    debitAccount: '1521',
    creditAccount: '331',
    attachedDocuments: 'Hoá đơn GTGT 0715',
    amountInWords: 'Hai triệu tám trăm sáu mươi lăm nghìn đồng chẵn',
    warehouseLocation: '',
    items: [
      {
        productName: 'Giấy A4 Double A 80gsm',
        productCode: 'VT-001',
        unit: 'Ram',
        quantity: 10,
        price: 78500,
      },
      {
        productName: 'Bìa hồ sơ còng 7cm',
        productCode: 'VT-028',
        unit: 'Cái',
        quantity: 20,
        price: 42000,
      },
      {
        productName: 'Mực in laser đen HP 76A',
        productCode: 'VT-014',
        unit: 'Hộp',
        quantity: 1,
        price: 1240000,
      },
    ],
    totalAmount: 10 * 78500 + 20 * 42000 + 1 * 1240000,
    createdAt: '2026-07-15T14:00:00.000Z',
  },
  {
    id: crypto.randomUUID(),
    code: 'PNK-20260722-008',
    warehouseName: 'Kho miền Nam',
    supplierName: 'Nhà phân phối Đông Á',
    receiptDate: '2026-07-22',
    unitName: 'CÔNG TY TNHH GIẢI PHÁP SỐ',
    department: 'Phòng kho vận',
    delivererName: 'Nguyễn Thị Hoa',
    invoiceNumber: 'HD-2026-0722',
    invoiceDate: '2026-07-22',
    debitAccount: '1521',
    creditAccount: '331',
    attachedDocuments: 'Hoá đơn GTGT 0722',
    amountInWords: 'Hai triệu bốn trăm tám mươi nghìn đồng chẵn',
    warehouseLocation: '',
    items: [
      {
        productName: 'Mực in laser đen HP 76A',
        productCode: 'VT-014',
        unit: 'Hộp',
        quantity: 2,
        price: 1240000,
      },
    ],
    totalAmount: 2 * 1240000,
    createdAt: '2026-07-22T09:00:00.000Z',
  },
  {
    id: crypto.randomUUID(),
    code: 'PNK-20260805-009',
    warehouseName: 'Kho tổng Hà Nội',
    supplierName: 'Văn phòng phẩm Hồng Hà',
    receiptDate: '2026-08-05',
    unitName: 'CÔNG TY TNHH GIẢI PHÁP SỐ',
    department: 'Phòng hành chính',
    delivererName: 'Lê Văn Cường',
    invoiceNumber: 'HD-2026-0805',
    invoiceDate: '2026-08-05',
    debitAccount: '1521',
    creditAccount: '331',
    attachedDocuments: 'Hoá đơn GTGT 0805',
    amountInWords: 'Hai triệu ba trăm năm mươi lăm nghìn đồng chẵn',
    warehouseLocation: '',
    items: [
      {
        productName: 'Giấy A4 Double A 80gsm',
        productCode: 'VT-001',
        unit: 'Ram',
        quantity: 30,
        price: 78500,
      },
    ],
    totalAmount: 30 * 78500,
    createdAt: '2026-08-05T08:00:00.000Z',
  },
  {
    id: crypto.randomUUID(),
    code: 'PNK-20260812-010',
    warehouseName: 'Kho miền Nam',
    supplierName: 'Công ty TNHH Thiết bị Văn phòng Minh Long',
    receiptDate: '2026-08-12',
    unitName: 'CÔNG TY TNHH GIẢI PHÁP SỐ',
    department: 'Phòng kho vận',
    delivererName: 'Trần Văn Bình',
    invoiceNumber: 'HD-2026-0812',
    invoiceDate: '2026-08-12',
    debitAccount: '1521',
    creditAccount: '331',
    attachedDocuments: 'Hoá đơn GTGT 0812',
    amountInWords: 'Hai triệu hai trăm chín mươi nghìn đồng chẵn',
    warehouseLocation: '',
    items: [
      {
        productName: 'Bìa hồ sơ còng 7cm',
        productCode: 'VT-028',
        unit: 'Cái',
        quantity: 25,
        price: 42000,
      },
      {
        productName: 'Mực in laser đen HP 76A',
        productCode: 'VT-014',
        unit: 'Hộp',
        quantity: 1,
        price: 1240000,
      },
    ],
    totalAmount: 25 * 42000 + 1 * 1240000,
    createdAt: '2026-08-12T10:00:00.000Z',
  },
  {
    id: crypto.randomUUID(),
    code: 'PNK-20260815-011',
    warehouseName: 'Kho tổng Hà Nội',
    supplierName: 'Nhà phân phối Đông Á',
    receiptDate: '2026-08-15',
    unitName: 'CÔNG TY TNHH GIẢI PHÁP SỐ',
    department: 'Phòng hành chính',
    delivererName: 'Nguyễn Thị Hoa',
    invoiceNumber: 'HD-2026-0815',
    invoiceDate: '2026-08-15',
    debitAccount: '1521',
    creditAccount: '331',
    attachedDocuments: 'Hoá đơn GTGT 0815',
    amountInWords: 'Hai trăm sáu mươi nghìn đồng chẵn',
    warehouseLocation: '',
    items: [
      {
        productName: 'Băng keo trong 5cm',
        productCode: 'VT-043',
        unit: 'Cuộn',
        quantity: 8,
        price: 15000,
      },
      {
        productName: 'Sổ tay lò xo A5',
        productCode: 'VT-052',
        unit: 'Quyển',
        quantity: 5,
        price: 28000,
      },
    ],
    totalAmount: 8 * 15000 + 5 * 28000,
    createdAt: '2026-08-15T09:30:00.000Z',
  },
]

const delay = (ms = 300) => new Promise((resolve) => setTimeout(resolve, ms))

function generateCode(): string {
  const today = new Date().toISOString().slice(0, 10).replace(/-/g, '')
  return `PNK-${today}-${String(receipts.length + 1).padStart(3, '0')}`
}

export async function getGoodsReceipts(): Promise<GoodsReceipt[]> {
  await delay()
  return receipts
}

export async function createGoodsReceipt(payload: GoodsReceiptFormValues): Promise<GoodsReceipt> {
  await delay()
  const totalAmount = payload.items.reduce((sum, item) => sum + item.quantity * item.price, 0)
  const receipt: GoodsReceipt = {
    id: crypto.randomUUID(),
    code: generateCode(),
    ...payload,
    totalAmount,
    createdAt: new Date().toISOString(),
  }
  receipts = [receipt, ...receipts]
  return receipt
}
