export const GOODS_RECEIPT_MESSAGE = {
  CREATED: 'Tạo phiếu nhập kho thành công',
  NOT_FOUND: 'Không tìm thấy phiếu nhập kho',
  WAREHOUSE_NAME_REQUIRED: 'Vui lòng nhập hoặc chọn kho nhập',
  WAREHOUSE_LOCATION_REQUIRED_FOR_NEW:
    'Kho này chưa có — vui lòng nhập địa điểm',
  SUPPLIER_NAME_REQUIRED: 'Vui lòng nhập hoặc chọn nhà cung cấp',
  RECEIPT_DATE_REQUIRED: 'Vui lòng chọn ngày nhập',
  ITEMS_REQUIRED: 'Cần ít nhất 1 sản phẩm trong phiếu nhập',
  PRODUCT_NAME_REQUIRED: 'Vui lòng nhập hoặc chọn sản phẩm',
  PRODUCT_CODE_REQUIRED: 'Vui lòng nhập mã số',
  ITEM_UNIT_REQUIRED: 'Vui lòng nhập đơn vị tính',
  QUANTITY_INVALID: 'Số lượng phải là số',
  QUANTITY_POSITIVE: 'Số lượng phải lớn hơn 0',
  PRICE_INVALID: 'Đơn giá phải là số',
  PRICE_NOT_NEGATIVE: 'Đơn giá không được âm',
  UNIT_NAME_REQUIRED: 'Vui lòng nhập đơn vị',
  DEPARTMENT_REQUIRED: 'Vui lòng nhập bộ phận',
  DELIVERER_NAME_REQUIRED: 'Vui lòng nhập họ và tên người giao',
  INVOICE_NUMBER_REQUIRED: 'Vui lòng nhập số hoá đơn',
  INVOICE_DATE_REQUIRED: 'Vui lòng chọn ngày hoá đơn',
  DEBIT_ACCOUNT_REQUIRED: 'Vui lòng nhập tài khoản nợ',
  CREDIT_ACCOUNT_REQUIRED: 'Vui lòng nhập tài khoản có',
  ATTACHED_DOCUMENTS_REQUIRED: 'Vui lòng nhập số chứng từ gốc kèm theo',
  AMOUNT_IN_WORDS_REQUIRED: 'Vui lòng nhập tổng số tiền bằng chữ',
  ID_INVALID: 'ID phiếu nhập kho không hợp lệ',
} as const;
